### ISSUE TITLE
dependencies error with django 4.1.9

### ISSUE THREAD

**Issue by valvin1** [mauricebauer/ctf-leaderboard#9]
```
ERROR: Cannot install -r requirements.txt (line 3) and asgiref==3.4.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested asgiref==3.4.1
    django 4.1.9 depends on asgiref<4 and >=3.5.2
```

changing asgiref version to `3.5.2` is ok.

**Comment by Gabriel-Goldschmitt** [comment]
#10 I created a pr with a update also I added the missing template.css

**Comment by mauricebauer** [comment]
@GoldschmittGabriel Please check if fixed on main branch and close issure if fixed. Thanks :)

**Comment by Gabriel-Goldschmitt** [comment]
retested it, should be fixed.

@valvin1 if you still have problems, please create a new issue, or reopen this issue.
